name = "test"

[dataset]
mapping = "8class"

[split]
train_num = 0.9

[model]
type = "som"

[fit]
train_epochs = 500
validation = false
pregenerate = true
initial_rate = 0.0001
drop = 0.5
epochs_drop = 50
num_workers = 12

[stat]
confusion_sizes = true

[dataset.names]
FCS = "decCLL-9F"
SOM = "output/mll-sommaps/sample_maps/jan19"

[dataset.filters]
counts = 10000
groups = [ "CLL", "MBL", "MCL", "PL", "LPL", "MZL", "FL", "HCL", "normal",]
tubes = [ 1, 2, 3,]
date_max = 2018-04-01

[model.train_args]
batch_size = 64
draw_method = "balanced"
epoch_size = 16000
sample_weights = false

[model.test_args]
batch_size = 32
draw_method = "sequential"
sample_weights = false

[model.compile]
epsilon = 1e-8

[model.loader.Map2DLoader]
pad_width = 1

[model.loader.FCSLoader]
subsample = 200
randomize = false

[model.loader.CountLoader]
datatype = "dataframe"
